services:
  myapp:
    build:
      context: .
    image: iamkashifyousuf/virus-analyzer:latest
    container_name: myapp
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    restart: unless-stopped
